use anyhow::{Context, Result, anyhow};
use clap::Parser;
use std::env;
use std::path::PathBuf;

/// Utility tool to delete auxiliary files generated by LaTeX
#[derive(Parser, Debug)]
#[command(version, about, long_about = None)]
pub struct Options {
    /// Target directory to clean auxiliary files from
    pub target_dir: Option<PathBuf>,

    /// Enable recursive processing of subdirectories.
    #[arg(long, default_value_t = false)]
    pub recursive: bool,

    /// Enable dry-run mode (i.e. no files will be deleted).
    #[arg(long, default_value_t = false)]
    pub dry_run: bool,

    /// Enable verbose logging.
    #[arg(short, long, default_value_t = false)]
    pub verbose: bool,
}

impl Options {
    /// Utility function to handle `option.target_dir`
    pub fn get_target_path(&self) -> Result<PathBuf> {
        let target_path = match &self.target_dir {
            Some(target_dir) => target_dir.clone(),
            None => env::current_dir().context("Failed to get current working directory")?,
        };

        if !target_path.exists() {
            return Err(anyhow!(
                "Specified target path '{}' does not exist.",
                target_path.display()
            ));
        }

        if !target_path.is_dir() {
            return Err(anyhow!(
                "Specified target path '{}' is not a directory.",
                target_path.display()
            ));
        }

        Ok(target_path)
    }
}
