use clap::Parser;
use std::path::PathBuf;

/// Utility tool to delete auxiliary files generated by LaTeX
#[derive(Parser, Debug)]
#[command(version, about, long_about = None)]
pub struct Options {
    /// Target directory to clean auxiliary files from
    pub target_dir: Option<PathBuf>,

    /// Recursively process subdirectories. When false, only process files in the target directory itself.
    #[arg(short, long, default_value_t = false)]
    pub recursive: bool,

    /// Enable dry-run mode. When true, no files will be deleted.
    #[arg(long, default_value_t = false)]
    pub dry_run: bool,
}
