use clap::Parser;
use std::fs;
use std::path::Path;
use walkdir::WalkDir;

/// Utility tool to delete auxiliary files generated by LaTeX
#[derive(Parser, Debug)]
#[command(version, about, long_about = None)]
struct Options {
    /// Target directory to clean auxiliary files from
    #[arg(short, long, default_value = ".")]
    target: String,

    /// Disable if you want to delete only files in the target directory
    #[arg(short, long, default_value_t = true)]
    recursive: bool,

    /// Enable if you want to delete files
    #[arg(short, long, default_value_t = false)]
    execute: bool,
}

// constants for matching
const SUFFIX_MATCH: &[&str] = &[".run.xml"];

const CONTAINS_MATCH: &[&str] = &[".synctex"];

const EXT_MATCH: &[&str] = &[
    "aux",
    "bbl",
    "log",
    "out",
    "toc",
    "lof",
    "lot",
    "fls",
    "fdb_latexmk",
    "blg",
    "bcf",
];

fn is_latex_aux(path: &Path) -> bool {
    let name = match path.file_name().and_then(|s| s.to_str()) {
        Some(n) => n,
        None => return false,
    };

    if SUFFIX_MATCH.iter().any(|s| name.ends_with(s)) {
        return true;
    }

    if CONTAINS_MATCH.iter().any(|s| name.contains(s)) {
        return true;
    }

    let ext = match path.extension().and_then(|s| s.to_str()) {
        Some(e) => e,
        None => return false,
    };

    EXT_MATCH.contains(&ext)
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let options = Options::parse();

    let walker = if options.recursive {
        WalkDir::new(&options.target)
    } else {
        WalkDir::new(&options.target).max_depth(1)
    };

    for entry in walker {
        let entry = entry?;
        let path = entry.path();

        if path.is_dir() {
            if let Some(name) = path.file_name().and_then(|s| s.to_str()) {
                if name.starts_with("_minted") {
                    if options.execute {
                        fs::remove_dir_all(path)?;
                        println!("Removed directory: {}", path.display());
                    } else {
                        println!("Would remove directory: {}", path.display());
                    }
                }
            }
        }

        if path.is_file() && is_latex_aux(path) {
            if options.execute {
                fs::remove_file(path)?;
                println!("Removed: {}", path.display());
            } else {
                println!("Would remove: {}", path.display());
            }
        }
    }

    Ok(())
}
