use clap::Parser;
use std::path::{Path, PathBuf};
use std::{env, fs};
use walkdir::WalkDir;

/// Utility tool to delete auxiliary files generated by LaTeX
#[derive(Parser, Debug)]
#[command(version, about, long_about = None)]
struct Options {
    /// Target directory to clean auxiliary files from
    target_dir: Option<PathBuf>,

    /// Recursively process subdirectories. When false, only process files in the target directory itself.
    #[arg(short, long, default_value_t = false)]
    recursive: bool,

    /// Enable dry-run mode. When true, no files will be deleted.
    #[arg(long, default_value_t = false)]
    dry_run: bool,
}

// constants for matching
const SUFFIX_MATCH: &[&str] = &[".run.xml", "-SAVE-ERROR"];
const EXT_MATCH: &[&str] = &[
    "aux",
    "bbl",
    "log",
    "out",
    "toc",
    "lof",
    "lot",
    "fls",
    "fdb_latexmk",
    "blg",
    "bcf",
];

fn is_latex_aux(path: &Path) -> bool {
    let name = match path.file_name().and_then(|s| s.to_str()) {
        Some(n) => n,
        None => return false,
    };

    if SUFFIX_MATCH.iter().any(|s| name.ends_with(s)) {
        return true;
    }

    let ext = match path.extension().and_then(|s| s.to_str()) {
        Some(e) => e,
        None => return false,
    };

    EXT_MATCH.contains(&ext)
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let options = Options::parse();
    let target_path = options
        .target_dir
        .unwrap_or_else(|| env::current_dir().expect("Failed to get current directory"));

    if !target_path.exists() {
        return Err(format!("Target path '{:#?}' does not exist", target_path).into());
    }

    if !target_path.is_dir() {
        return Err(format!("Target path '{:#?}' is not a directory", target_path).into());
    }

    if options.dry_run {
        println!("INFO: Running in dry-run mode. No files will be deleted.");
    }

    let mut walker = if options.recursive {
        WalkDir::new(target_path).follow_links(false).into_iter()
    } else {
        WalkDir::new(target_path)
            .max_depth(1)
            .follow_links(false)
            .into_iter()
    };

    while let Some(entry_result) = walker.next() {
        let entry = entry_result?;
        let path = entry.path();
        let file_type = entry.file_type();

        if file_type.is_symlink() {
            continue;
        }

        if file_type.is_dir() {
            if let Some(name) = path.file_name().and_then(|s| s.to_str())
                && name.starts_with("_minted")
            {
                if options.dry_run {
                    println!("Would remove directory: {}", path.display());
                } else {
                    fs::remove_dir_all(path)?;
                    println!("Removed directory: {}", path.display());
                }
                walker.skip_current_dir();
                continue;
            }
        } else if file_type.is_file() && is_latex_aux(path) {
            if options.dry_run {
                println!("Would remove: {}", path.display());
            } else {
                fs::remove_file(path)?;
                println!("Removed: {}", path.display());
            }
        }
    }

    Ok(())
}
